// <auto-generated />
using System;
using FacturiApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacturiApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FacturiApp.Models.ClientEntity", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("FacturiApp.Models.FacturaEntity", b =>
                {
                    b.Property<int>("NrFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NrFactura"));

                    b.Property<DateTime>("DataFactura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<string>("Observatii")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NrFactura");

                    b.HasIndex("IdClient");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("FacturiApp.Models.PlataEntity", b =>
                {
                    b.Property<int>("IdPlata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlata"));

                    b.Property<DateTime>("DataPlata")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodaPlata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrFactura")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Suma")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPlata");

                    b.HasIndex("NrFactura");

                    b.ToTable("Plati");
                });

            modelBuilder.Entity("FacturiApp.Models.ProdusEntity", b =>
                {
                    b.Property<int>("IdProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdus"));

                    b.Property<string>("NumeProdus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitateMasura")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProdus");

                    b.ToTable("Produse");
                });

            modelBuilder.Entity("FacturiApp.Models.ProdusFacturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<int>("NrFactura")
                        .HasColumnType("int");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NrFactura");

                    b.ToTable("ProdusFactura");
                });

            modelBuilder.Entity("FacturiApp.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FacturiApp.Models.FacturaEntity", b =>
                {
                    b.HasOne("FacturiApp.Models.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FacturiApp.Models.PlataEntity", b =>
                {
                    b.HasOne("FacturiApp.Models.FacturaEntity", "Factura")
                        .WithMany()
                        .HasForeignKey("NrFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturiApp.Models.ProdusFacturaEntity", b =>
                {
                    b.HasOne("FacturiApp.Models.FacturaEntity", "Factura")
                        .WithMany("ProduseFactura")
                        .HasForeignKey("NrFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturiApp.Models.FacturaEntity", b =>
                {
                    b.Navigation("ProduseFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
