// <auto-generated />
using System;
using FacturaService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacturaService.Migrations
{
    [DbContext(typeof(FacturaDbContext))]
    [Migration("20260604195032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FacturaService.Models.FacturaEntity", b =>
                {
                    b.Property<int>("NrFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NrFactura"));

                    b.Property<DateTime>("DataFactura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<string>("Observatii")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NrFactura");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("FacturaService.Models.ProdusFacturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<int>("NrFactura")
                        .HasColumnType("int");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NrFactura");

                    b.ToTable("ProdusFactura");
                });

            modelBuilder.Entity("FacturaService.Models.ProdusFacturaEntity", b =>
                {
                    b.HasOne("FacturaService.Models.FacturaEntity", "Factura")
                        .WithMany("ProduseFactura")
                        .HasForeignKey("NrFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturaService.Models.FacturaEntity", b =>
                {
                    b.Navigation("ProduseFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
